### ISSUE TITLE
Forced to add a trigger word while connecting to Slack

### ISSUE THREAD

**Issue by Bybeez** [voyages-sncf-technologies/tock#248]
When connecting a bot to a Slack Workspace, the bot can't instantiate the SlackMessageIn if the trigger_word field is null. So we can't connect it without putting a trigger word in the slack outgoing webhook, wich is still sent to the nlp.

**Comment by LTMXcitrus** [comment]
Hi @Bybeez,
I'm away from my personnal computer (on which I have everything installed). So I won't be able to look into it until tonight (at the very best) or next week.

Meanwhile, can you just tell me:
"[the trigger word] is still sent to the nlp" -> is this something you experienced ? Because the connector is supposed to remove the trigger word before sending the message to the NLP layer. So if it's just something you feared, please try anyway :)

If you want to use your bot in a specific channel (1-to-1 messages only), you're right, the trigger word is useless, I'll prepare a PR to correct that.

**Comment by LTMXcitrus** [comment]
After some investigations:

If you leave the "trigger word" field empty, the bot will react to every new message in the channel your Outgoing webhook is watching. Including its own messages, leading to infinite loop of messages.
That's why you want a trigger word.
When choosing a trigger word, be sure to choose something that the bot will never say, or you will fallback to the same situation described above. (I recommend something starting with a "@", as if you wanted to notify a channel member)

The trigger word is removed from the message before being sent to the NLP layer.

So: You can't instantiate a SlackMessageIn without a trigger word, for the reason described above. Meaning that you must indicate a trigger word when creating your Outgoing webhook.
This trigger word will not affect the work of your bot as it is removed from the message.

**Comment by LTMXcitrus** [comment]
@vsct-jburet, I think you can close this issue 😄

**Comment by Bybeez** [comment]
Isn't it possible to prevent the bot from answering it's own messages ? Having the trigger word is not very natural and user friendly, and it would be awesome to get rid of it if possible

**Comment by LTMXcitrus** [comment]
I don't really agree as Slack is a multi-user messaging service. It means when you're using slack, you speak to several people at the same time. How is the bot supposed to know when you're waiting an answer from him specifically ?
But maybe I don't see what is your purpose here :)

**Comment by Bybeez** [comment]
I'd put the bot in a specific channel, so users would use this channel only to talk to the bot. It seems coherent, since it's a conversationnal bot to limit it to a single channel where people would try to have a conversation with it in the most natural way. Maybe I'm overthinking it ^^

**Comment by LTMXcitrus** [comment]
I think I see what you mean, but then I see that as a new feature rather thant a bug :)

Feel free to contribute ;)
